In [5]:
import pandas as pd
data=pd.read_excel('C:/Users/user/Downloads/데이터통합.xlsx')
data

자치구     동   2021   2022  상주인구 증가율  프랜차이즈점 개수  평균영업기간(년)    개업    폐업  \
0    종로구   사직동   9543   9370 -0.018128      206.0        3.4  47.0  31.0   
1    종로구   삼청동   2530   2441 -0.035178       48.0        3.3  15.0  11.0   
2    종로구   부암동   9819   9488 -0.033710       36.0        3.3  14.0   6.0   
3    종로구   평창동  18308  18087 -0.012071       35.0        3.6   8.0  12.0   
4    종로구   무악동   8380   8210 -0.020286       17.0        3.3   4.0   1.0   
..   ...   ...    ...    ...       ...        ...        ...   ...   ...   
420  강동구  둔촌1동    134    132 -0.014925        6.0        3.1   0.0   1.0   
421  강동구  둔촌2동  25188  24529 -0.026163       85.0        3.1  15.0  12.0   
422  강동구  암사1동  34959  34352 -0.017363       96.0        2.9  33.0  20.0   
423  강동구  천호2동  33849  33070 -0.023014      243.0        3.1  55.0  46.0   
424  강동구    길동  46160  45554 -0.013128      247.0        2.9  54.0  41.0   

     창폐업수  2022년 유동인구  2021년 유동인구   유동인구 증가율  2021매출액  2022매출액     매출액증가율  
0      78     20258.0     22475.0  -9.864294    725.0    830.0  14.482759  
1      26      4265.0      4184.0   1.935946    207.0    241.0  16.425121  
2      20      4459.0      4692.0  -4.965899     71.0     61.0 -14.084507  
3      20      1090.0      1493.0 -26.992632    155.0    163.0   5.161290  
4       5     34149.0     36031.0  -5.223280     86.0     88.0   2.325581  
..    ...         ...         ...        ...      ...      ...        ...  
420     1      9388.0     12552.0 -25.207138      8.0     14.0  75.000000  
421    27     45727.0     41739.0   9.554613    332.0    332.0   0.000000  
422    53    121891.0    119996.0   1.579219    358.0    363.0   1.396648  
423   101     58492.0     58902.0  -0.696071   1527.0   1374.0 -10.019646  
424    95    101194.0     94971.0   6.552527    933.0   1005.0   7.717042  

[425 rows x 16 columns]

In [6]:
data1=data.loc[:,['동','상주인구 증가율','프랜차이즈점 개수','평균영업기간(년)','창폐업수','유동인구 증가율','매출액증가율']]

In [8]:
data1.isna().sum()             #항동 2022년 5월 

동            0
상주인구 증가율     0
프랜차이즈점 개수    1
평균영업기간(년)    1
창폐업수         0
유동인구 증가율     1
매출액증가율       1
dtype: int64

In [10]:
data1.dropna(axis=0,inplace=True)

In [11]:
창폐업_횟수=[]
for row in data1['창폐업수']:
    if row >= data1['창폐업수'].mean()+2*data1['창폐업수'].std():
        창폐업_횟수.append(2)
    elif row >=data1['창폐업수'].mean()+data1['창폐업수'].std() and row <data1['창폐업수'].mean()+2*data1['창폐업수'].std() :
        창폐업_횟수.append(1)
    elif row >=data1['창폐업수'].mean() and  row <data1['창폐업수'].mean()+data1['창폐업수'].std() :
        창폐업_횟수.append(-1)
    else:
        창폐업_횟수.append(-2)
data1['창폐업 횟수'] = 창폐업_횟수    

In [12]:
프랜차이즈_업체_수=[]
for row in data1['프랜차이즈점 개수']:
    if row >= data1['프랜차이즈점 개수'].mean()+2*data1['프랜차이즈점 개수'].std():
        프랜차이즈_업체_수.append(2)
    elif row >=data1['프랜차이즈점 개수'].mean()+data1['프랜차이즈점 개수'].std() and row <data1['프랜차이즈점 개수'].mean()+2*data1['프랜차이즈점 개수'].std() :
        프랜차이즈_업체_수.append(1)
    elif row >=data1['프랜차이즈점 개수'].mean() and  row <data1['프랜차이즈점 개수'].mean()+data1['프랜차이즈점 개수'].std() :
        프랜차이즈_업체_수.append(-1)
    else:
        프랜차이즈_업체_수.append(-2)
        
data1['프랜차이즈 업체 수'] = 프랜차이즈_업체_수       

In [15]:
유동인구_증가율=[]
for row in data1['유동인구 증가율']:
    if row >= data1['유동인구 증가율'].mean()+2*data1['유동인구 증가율'].std():
        유동인구_증가율.append(2)
    elif row >=data1['유동인구 증가율'].mean()+data1['유동인구 증가율'].std() and row <data1['유동인구 증가율'].mean()+2*data1['유동인구 증가율'].std() :
        유동인구_증가율.append(1)
    elif row >=data1['유동인구 증가율'].mean() and  row <data1['유동인구 증가율'].mean()+data1['유동인구 증가율'].std() :
        유동인구_증가율.append(-1)
    else:
        유동인구_증가율.append(-2)
        
data1['유동인구_증가율'] = 유동인구_증가율      

In [16]:
매출액_증가율=[]
for row in data1['매출액증가율']:
    if row >= data1['매출액증가율'].mean()+2*data1['매출액증가율'].std():
        매출액_증가율.append(2)
    elif row >=data1['매출액증가율'].mean()+data1['매출액증가율'].std() and row <data1['매출액증가율'].mean()+2*data1['매출액증가율'].std() :
        매출액_증가율.append(1)
    elif row >=data1['매출액증가율'].mean() and  row <data1['매출액증가율'].mean()+data1['매출액증가율'].std() :
        매출액_증가율.append(-1)
    else:
        매출액_증가율.append(-2)
        
data1['매출액 증가율'] = 매출액_증가율      

In [17]:
#역변환
상주인구_증가율=[]
for row in data1['상주인구 증가율']:
    if row <= data1['상주인구 증가율'].mean()-2*data1['상주인구 증가율'].std():
        상주인구_증가율.append(2)
    elif row <=data1['상주인구 증가율'].mean()-data1['상주인구 증가율'].std() and row >data1['상주인구 증가율'].mean()-2*data1['상주인구 증가율'].std() :
        상주인구_증가율.append(1)
    elif row <=data1['상주인구 증가율'].mean() and  row >data1['상주인구 증가율'].mean()-data1['상주인구 증가율'].std() :
        상주인구_증가율.append(-1)
    else:
        상주인구_증가율.append(-2)
        
data1['상주인구_증가율'] = 상주인구_증가율       

In [18]:
#역변환
평균_영업기간=[]
for row in data1['평균영업기간(년)']:
    if row <= data1['평균영업기간(년)'].mean()-2*data1['평균영업기간(년)'].std():
        평균_영업기간.append(2)
    elif row <=data1['평균영업기간(년)'].mean()-data1['평균영업기간(년)'].std() and row >data1['평균영업기간(년)'].mean()-2*data1['평균영업기간(년)'].std() :
        평균_영업기간.append(1)
    elif row <=data1['평균영업기간(년)'].mean() and  row >data1['평균영업기간(년)'].mean()-data1['평균영업기간(년)'].std() :
        평균_영업기간.append(-1)
    else:
        평균_영업기간.append(-2)
        
data1['평균 영업기간'] = 평균_영업기간  

In [19]:
data1

동  상주인구 증가율  프랜차이즈점 개수  평균영업기간(년)  창폐업수   유동인구 증가율     매출액증가율  창폐업 횟수  \
0     사직동 -0.018128      206.0        3.4    78  -9.864294  14.482759      -1   
1     삼청동 -0.035178       48.0        3.3    26   1.935946  16.425121      -2   
2     부암동 -0.033710       36.0        3.3    20  -4.965899 -14.084507      -2   
3     평창동 -0.012071       35.0        3.6    20 -26.992632   5.161290      -2   
4     무악동 -0.020286       17.0        3.3     5  -5.223280   2.325581      -2   
..    ...       ...        ...        ...   ...        ...        ...     ...   
420  둔촌1동 -0.014925        6.0        3.1     1 -25.207138  75.000000      -2   
421  둔촌2동 -0.026163       85.0        3.1    27   9.554613   0.000000      -2   
422  암사1동 -0.017363       96.0        2.9    53   1.579219   1.396648      -1   
423  천호2동 -0.023014      243.0        3.1   101  -0.696071 -10.019646       1   
424    길동 -0.013128      247.0        2.9    95   6.552527   7.717042       1   

     프랜차이즈 업체 수  상주인구_증가율  평균 영업기간  유동인구_증가율  매출액 증가율  
0            -1        -1       -2        -2       -1  
1            -2        -1       -2        -1       -1  
2            -2        -1       -2        -2       -2  
3            -2        -1       -2        -2       -1  
4            -2        -1       -2        -2       -2  
..          ...       ...      ...       ...      ...  
420          -2        -1       -1        -2        2  
421          -2        -1       -1         1       -2  
422          -2        -1       -1        -1       -2  
423           1        -1       -1        -1       -2  
424           1        -1       -1        -1       -1  

[424 rows x 13 columns]

In [20]:
data2=data1.loc[:,['프랜차이즈 업체 수','상주인구_증가율','평균 영업기간','창폐업 횟수','유동인구_증가율','매출액 증가율']]

In [21]:
data3= print(data2.to_numpy())

[[-1 -1 -2 -1 -2 -1]
 [-2 -1 -2 -2 -1 -1]
 [-2 -1 -2 -2 -2 -2]
 ...
 [-2 -1 -1 -1 -1 -2]
 [ 1 -1 -1  1 -1 -2]
 [ 1 -1 -1  1 -1 -1]]


In [22]:
import numpy as np
data3=data2.to_numpy(copy=True)
b = np.array([0.15, 0.134, 0.134, 0.141,0.202, 0.239])
c=np.dot(data3, b)
d=c.tolist()

In [23]:
data1['지표값'] = d       

In [24]:
data5=data1.loc[:,['동','지표값']]
data5

동    지표값
0     사직동 -1.336
1     삼청동 -1.425
2     부암동 -1.866
3     평창동 -1.627
4     무악동 -1.866
..    ...    ...
420  둔촌1동 -0.776
421  둔촌2동 -1.126
422  암사1동 -1.389
423  천호2동 -0.657
424    길동 -0.418

[424 rows x 2 columns]

In [25]:
data5.to_excel('C:/Users/user/Downloads/젠트리피케이션지표.xlsx')